
//PING API
###
POST http://127.0.0.1:8181/v1/troubleshoot/ping
Accept: application/json
Content-Type: application/json

{
    "ip":"127.0.0.1"
}

//NMAP API
###
POST http://127.0.0.1:8181/v1/troubleshoot/nmap
Accept: application/json
Content-Type: application/json

{
    "ip":"127.0.0.1"
}



//TRACEPATH API
###
POST http://127.0.0.1:8181/v1/troubleshoot/tracepath
Accept: application/json
Content-Type: application/json

{
    "ip":"127.0.0.1"
}


//TELNET API
###
POST http://127.0.0.1:8181/v1/troubleshoot/telnet
Accept: application/json
Content-Type: application/json


//UDP API
###
POST http://127.0.0.1:8181/v1/troubleshoot/udp
Accept: application/json
Content-Type: application/json




//NSLOOKUP API
###
POST http://127.0.0.1:8181/v1/troubleshoot/nslookup
Accept: application/json
Content-Type: application/json

{
    "ip":"google.com"
}




//IPCONFIG API
###
GET http://127.0.0.1:8181/v1/troubleshoot/ipconfig
Accept: application/json
Content-Type: application/json



//NETSTAT API
###
GET http://127.0.0.1:8181/v1/troubleshoot/netstat
Accept: application/json
Content-Type: application/json


